### ISSUE TITLE
Chests become invisible and their contents are cleared

### ISSUE THREAD

**Issue by samfces** [Paul19988/Advanced-Slime-World-Manager#112] opened 2022-03-22 17:23 UTC
**Describe the issue**
The error is simple to explain. I have a survival server in which each player has a 700x700 world that is managed by ASWM. It can be the case that the chests become invisible and at the same time their content is deleted.

**Spigot version**
Paper 1.17.1

**Plugin version**
2.7.0 SNAPSHOT

**How to reproduce**
I have no way to reproduce it. This bug appears randomly.
Video clip of the bug: [HERE](https://cdn.discordapp.com/attachments/895730080343556126/955587104073723944/Minecraft_1.17.1_-_Multijugador_servidor_de_terceros_2022-03-21_19-00-55.mp4)
Bukkit.yml: https://paste.minebox.es/uyomupayim.yaml
Paper.yml: https://paste.minebox.es/qahemeziva.yaml
Purpur.yml: https://paste.minebox.es/ubiyudoron.yaml
Spigot.yml: https://paste.minebox.es/ewuzubivik.yaml

**Crash reports (if available)**

**Comment by CommandDan** [comment] 2022-03-22 18:11
That may not be due to ASWM as I have seen that happen on other servers not using ASWM before. But I am not denying it still could be

**Comment by samfces** [comment] 2022-03-22 18:12
Apparently something similar happens with spawners. A zombie spawner turns into a pig spawner randomly so the problem must be related to Block Datas in general.

**Comment by raphtnt** [comment] 2022-03-22 18:34
Hello, I also have the same problem if you have a solution I would be interested

**Comment by aleexgheorghe** [comment] 2022-03-22 21:00
Hello! 

Today I have been talking on the community discord and the same problem happens to me, really my intention is to help this not to happen anymore, in my case it spoils the whole project we were doing and it is a terrible thing. Philipp asked me to please attach much more information about it. 

1- The infrastructure I use is somewhat simple, it is not very mysterious. We save the world on a storage server connected via NFS to the machines where we have our modality. 

2- The loading and saving of data is correct, it would be very rare that we do something wrong on our part as it only happens specifically with chests and spawners. As @CommandDan and my colleague @samfces says it is something related to the block data. The [load ](https://paste.minebox.es/okogigoyol.typescript) is generated in this way. The download is done with the bukkit download code (the one that comes with it).

3- I don't think the hardware and servers are the problem. We use OVH Advance and Infraestructure servers, all the traffic is done through private network and we don't have any kind of problem in the whole network (+1600 people), it is something rare that this happens.

4- WARNING: As of today we are using the version we downloaded on January 4, 2022, we will try to upgrade to [this new version](https://dl.rapture.pw/ASWM/pull/111/c20548772644a0a9184a4592190223b0a58b2ce5/).

5- A user reports me that he doesn't understand when it happens but you have to take into account that it happens in CHUNKS in particular. The spawners are lost (they become pigs again) and especially the theme of the chests become invisible and lose things. A strange case is that a chest was in the middle of a chunk with another one. Half of the chest was unreachable and the other half was not, so when it was opened it was updated and things were kept. https://prnt.sc/C7l1TScKwdEy, in this same chunk happened, including spawners and chests.

   - In another case, a user reported me that only half of this chest disappeared, I assume that the other half did not happen because it is in an itemhopper https://prnt.sc/YZvIqg4w0M1L
   - In another case, we can see that it looks like this: [Video
](https://cdn.discordapp.com/attachments/895730080343556126/955933823407906906/Minecraft_1.17.1_-_Multijugador_servidor_de_terceros_2022-03-22_17-58-11.mp4)
6- I attach timmings if necessary: https://timings.aikar.co/?id=310ee9492b1c40bcbad6a3395bd70f24

**Comment by Owen1212055** [comment] 2022-03-23 00:23
Can you guys tell us what exact build you guys are using? Is it the 1.18 PR 1.17 support or just the latest version.

**Comment by Owen1212055** [comment] 2022-03-23 00:49
I recommend waiting before updating to the new version, I need to still work to make sure 1.17 works smoothly. I'll get to work making that nicer so you are able to test updating, because it should be noted that the newest branch has a large amount of changes.

**Comment by aleexgheorghe** [comment] 2022-03-23 10:49
Hello!

Earlier tonight Paul told me to try the latest [build](https://prnt.sc/4vZZ3B8wj9pE) he made and test it on my server. 

I will continue to comment on this issue in case it happens to me again. Thanks @Paul19988

**Comment by Owen1212055** [comment] 2022-03-23 23:39
Yeah so, we are gonna need a lot of testing in order to figure out this issue.
If possible, try to figure out a way to reproduce it consistently as well... since "randomly" disappearing tile entities is NOT fun to fix. :(

**Comment by aleexgheorghe** [comment] 2022-03-24 07:52
Hi @Owen1212055 !

No problem at all, we will work to find the final way, that's for sure! 

Thank you very much for everything, I will update this issue with test results over the next few days.

**Comment by aleexgheorghe** [comment] 2022-03-24 20:21
Day 02 - Users have not reported anything to me again. Apparently @raphtnt is actively working on developing his server privately and says it hasn't happened again. 

I'll wait a couple more days - thanks a lot team!

**Comment by jok-dev** [comment] 2022-03-25 19:35
This was fixed by this commit https://github.com/Paul19988/Advanced-Slime-World-Manager/commit/a39347ece2c1104fc008870cc5c288660e09ebc6

Essentially because chunks are reused, we have to stop Minecraft clearing all tiles when the chunk unloads, which is the default behaviour.

**Comment by aleexgheorghe** [comment] 2022-03-25 19:43
Yes, I know, but I had not closed it because, well, I was waiting to see if it would happen again.

There is one thing that happens to me and it's the same thing but with items frames the same thing happens to me. They are deleted out of the blue

**Comment by jok-dev** [comment] 2022-03-25 19:47
> Yes, I know, but I had not closed it because, well, I was waiting to see if it would happen again.
> 
> There is one thing that happens to me and it's the same thing but with items frames the same thing happens to me. They are deleted out of the blue

Does it also happen with other entities, or just item frames? I have a fix for entities disapearing, not sure if it's on here or not. Basically the same issue, reusing chunks and not adding back entities when loading the chunk again after it has been unloaded.

**Comment by Owen1212055** [comment] 2022-03-25 19:53
Do you mind sharing your diff?

**Comment by jok-dev** [comment] 2022-03-25 19:57
I can absolutely, need to push though and not at my pc, will try do it ASAP. The general gist is creating a custom SlimeEntityStorage that saves and stores entities in memory between chunk unload-load, and then the entities can be loaded from the in-memory storage when the nms chunk is reused and loaded. You need this because entities are cleared completely from memory when a chunk is unloader, and I don't think it's a good idea to just keep unloaded entities in the world, as it could lead to weird behaviour.

**Comment by aleexgheorghe** [comment] 2022-03-26 20:18
Hello!

Unfortunately the problem in 1.17.1 remains the same and user chests continue to disappear without explanation. What I have been told, and as a curiosity. 

If you have a farm and hoppers that go to your chests, all the items get stuck in the hoppers, it's like the entity of the block is dead and everything inside is resected.

It's a really serious problem but no one of my users can find a pattern to it.

**Comment by Owen1212055** [comment] 2022-03-27 16:29
> Hello!
> 
> Unfortunately the problem in 1.17.1 remains the same and user chests continue to disappear without explanation. What I have been told, and as a curiosity.
> 
> If you have a farm and hoppers that go to your chests, all the items get stuck in the hoppers, it's like the entity of the block is dead and everything inside is resected.
> 
> It's a really serious problem but no one of my users can find a pattern to it.

Yeah, the issue is the tile entity is disappearing, but it's hard to exactly understand WHY this might be happening.

**Comment by jok-dev** [comment] 2022-03-27 16:32
> > Hello!
> > Unfortunately the problem in 1.17.1 remains the same and user chests continue to disappear without explanation. What I have been told, and as a curiosity.
> > If you have a farm and hoppers that go to your chests, all the items get stuck in the hoppers, it's like the entity of the block is dead and everything inside is resected.
> > It's a really serious problem but no one of my users can find a pattern to it.
> 
> Yeah, the issue is the tile entity is disappearing, but it's hard to exactly understand WHY this might be happening.

The reason this happens is when the block type for a chest is in a world but the block state does not exist.

**Comment by aleexgheorghe** [comment] 2022-03-27 16:33
What about this? It happens in any type of version, doesn't it? 1.17x / 1.18x?

**Comment by Owen1212055** [comment] 2022-03-27 16:35
I've been testing on 1.17, where I unload chunks with chests in them, reload them, try to load unsaved chunks, etc.
And every time the chests seem to be fine here.

**Comment by jok-dev** [comment] 2022-03-27 16:36
> I've been testing on 1.17, where I unload chunks with chests in them, reload them, try to load unsaved chunks, etc. And every time the chests seem to be fine here.

Do the chunks stay loaded? Or are they unloading when you leave the chunks

**Comment by Owen1212055** [comment] 2022-03-27 16:38
> > I've been testing on 1.17, where I unload chunks with chests in them, reload them, try to load unsaved chunks, etc. And every time the chests seem to be fine here.
> 
> Do the chunks stay loaded? Or are they unloading when you leave the chunks

It should be noted that chunks near (0,0) will always still be loaded due to paper mechanics.
No, they are unloaded when I fly very far away however when the chunk is reloaded tile entities seem to be there and it's just fine.

Other than that I have no idea what could be causing this here, so further testing and possible slime worlds in which this is occurring would be appreicated. 

Additionally, i'd like to know...
- How often are you saving the slime world?
- How large is the slime world? (are chunks loaded all the time)
- Does your slime world always have at least 1 person in it?

**Comment by aleexgheorghe** [comment] 2022-03-27 16:41
> > > He estado probando en 1.17, donde descargo fragmentos con cofres, los recargo, trato de cargar fragmentos no guardados, etc. Y cada vez que los cofres parecen estar bien aquí.
> > 
> > 
> > ¿Los trozos permanecen cargados? ¿O se están descargando cuando dejas los trozos?
> 
> Cabe señalar que los fragmentos cercanos a (0,0) siempre se cargarán debido a la mecánica del papel. No, se descargan cuando vuelo muy lejos, sin embargo, cuando se vuelve a cargar el fragmento, las entidades de mosaico parecen estar allí y está bien.
> 
> Aparte de eso, no tengo idea de qué podría estar causando esto aquí, por lo que se agradecerían más pruebas y posibles mundos de limo en los que esto esté ocurriendo.
> 
> Además me gustaría saber...
> 
> * ¿Con qué frecuencia estás salvando el mundo del limo?
> * ¿Qué tan grande es el mundo del limo? (son trozos cargados todo el tiempo)
> * ¿Tu mundo de limo siempre tiene al menos 1 persona en él?

In my case I use 1.17.1 and it doesn't happen every time I download or load the chunk. It happens every time the world is LOADED. How so? Whenever a player disconnects from the mode and spends more than five out of it, the world unloads to avoid unnecessary load inside the servers.

It happens with barrels, chests, frames, paintings and rarely animals. Actually let's say it happens with any entity. The world is saved every 30 minutes automatically. 

All the problem happens when the world is loaded or saved, that's as far as I could get, with the world loaded none of them told me anything.

**Comment by aleexgheorghe** [comment] 2022-03-27 17:31
I have been asking my community and so it is, all this happens when the world is downloaded (with this I understand that the problem can happen when saving or when loading, all users have reported me the same thing every time, it has never happened online).

Thank you very much

**Comment by jok-dev** [comment] 2022-03-27 18:54
> > > I've been testing on 1.17, where I unload chunks with chests in them, reload them, try to load unsaved chunks, etc. And every time the chests seem to be fine here.
> > 
> > 
> > Do the chunks stay loaded? Or are they unloading when you leave the chunks
> 
> It should be noted that chunks near (0,0) will always still be loaded due to paper mechanics. No, they are unloaded when I fly very far away however when the chunk is reloaded tile entities seem to be there and it's just fine.
> 
> Other than that I have no idea what could be causing this here, so further testing and possible slime worlds in which this is occurring would be appreicated.
> 
> Additionally, i'd like to know...
> 
> * How often are you saving the slime world?
> * How large is the slime world? (are chunks loaded all the time)
> * Does your slime world always have at least 1 person in it?

A good place to start might be to not call NMSSlimeChunk#getTileEntities async, this method loops through chunk tiles, which is backed by a regular HashMap, and therefore cannot be looped over from a thread other than the main mc one. Especially if this user is doing 30-minutely saves, that means that the chunk can be saved during a tile entity tick.

**Comment by aleexgheorghe** [comment] 2022-03-27 19:14
Hello!

I would be happy to help test all the changes that are made regarding the ASWM, it really is a project that I love and I'm using it in my community. I have even contributed money so that it can continue to be sustained, little but something is something. 

As you say @Elioby , couldn't you apply a change and have them review it? In principle, a hasmap if I understand correctly can not be modified at the same time. Using a ConcurrentHashMap, could you solve the problem? 

Actually this happens frequently and is something serious for servers using it for SkyBlock/Survival. Thank you very much once again for reading me. I'm sure that together we can come up with a solution.

**Comment by ComputerNerd100** [comment] 2022-03-27 19:27
The HashMap and concurrent access point is a good one to raise, and this is something we'll look into.
Unfortunately, this HashMap comes from the Minecraft Server and not from our code, so we can't change it (easily at least) to a ConcurrentHashMap.
However we'll review ways we can test if this is the issue and then look at a workaround :)

**Comment by jok-dev** [comment] 2022-03-27 19:48
The way Paper does it is by saving any data you can't access async in an "AsyncSaveData" object synchronously before the save: https://github.com/PaperMC/Paper/blob/1c5f8b0fcecd4352d7a9ec80bee97b322ba8c8e4/patches/server/0253-Asynchronous-chunk-IO-and-loading.patch#L3064

Might be possible to just re-use that system, or just create a similar one.

**Comment by aleexgheorghe** [comment] 2022-03-28 11:52
Hello!

Hopefully we can find a fix for this problem. I have been reported another bug that I relate to this same problem. Apparently if you have spawners of any kind, in a totally random way (like random chests) practically the same thing happens.

Thanks guys!

**Comment by Owen1212055** [comment] 2022-03-28 12:59
Later today I will be rewriting the saving process in hopes of resolving this issue. Stay tuned

**Comment by Owen1212055** [comment] 2022-03-29 00:58
The attempted fix for this has been pushed  https://github.com/Paul19988/Advanced-Slime-World-Manager/commit/5c478961d5a1a65c6b500a19560c3605838d4e2d https://canary.discord.com/channels/741733106930810950/741741550383398942/958167684237897728

PLEASE make sure to read [this](https://github.com/Paul19988/Advanced-Slime-World-Manager/pull/97#issuecomment-1081292337) first.

**Comment by aleexgheorghe** [comment] 2022-03-29 16:56
> The attempted fix for this has been pushed [5c47896](https://github.com/Paul19988/Advanced-Slime-World-Manager/commit/5c478961d5a1a65c6b500a19560c3605838d4e2d) https://canary.discord.com/channels/741733106930810950/741741550383398942/958167684237897728
> 
> PLEASE make sure to read [this](https://github.com/Paul19988/Advanced-Slime-World-Manager/pull/97#issuecomment-1081292337) first.

Hello!

First of all thank you for the change made, I am checking everything in detail to see if it happens again. Also, I have bothered to completely reset my paperspigot settings to avoid configuration issues (I am re-attaching them again).

- Bukkit: https://paste.minebox.es/ozucawikig.yaml
- Spigot: https://paste.minebox.es/unegenequn.yaml
- Server: https://paste.minebox.es/behawuseri.ini
- Papper: https://paste.minebox.es/igoxuduwov.yaml

I have bothered to take 4 chunks that are together to be able to perform the tests. In these chunks I put the following tileentities:

- Chests
- Enderchest
- Mobs
- ItemFrames
- Frames

In all my tests everything but the chests have disappeared. The version of my paperspigot, in case any doubts arise is the latest one related to version 1.17.1
![image](https://user-images.githubusercontent.com/46347629/160664876-71faba78-7f98-4b3c-98aa-052fc26a2a3b.png)

I hope I can contribute in solving the problem. I must admit that it has not given me problems in saving and/or loading the world after all the change, it works but I still have that problem. If you need anything else, feel free to let me know. I could record you a video if you prefer.

Best regards! I'm sure you are very close to a solution.

**Comment by aleexgheorghe** [comment] 2022-03-29 17:27
I have made a [video ](https://youtu.be/CHJ-g2EahEs) showing part of the console so that it can be seen that I am not doing something wrong.

This video will probably be deleted in 24h. My intention is to recreate the failure so that you can have some idea of what is happening to me. 

Thank you very much!

**Comment by samfces** [comment] 2022-04-04 18:17
Hello again! I have just performed several tests on our side to check where the problem could be and, apparently, it is a bug related to saving entities that are in unloaded chunks.

Currently, in our plugin, worlds can be saved and unloaded in two different ways:
- Using the /stop command in which worlds are saved instantly.
- When a player disconnects and the world becomes inactive for at least 2 minutes.

In the first case and after unloading the world, restarting the server and reloading the world again there is no problem. The entities are saved and loaded correctly and without losses since the test chunk where the entities are located is occupied and loaded by the player.

The problem arises in this second case. When the player is disconnected the chunk is unloaded and, when saving, no entity appears as I have been able to verify in some debugs that I have added.

I could only check the first case by adding a tile entity in a distant chunk and disconnecting far away from it to see if it is still removed.

**Comment by Paul19988** [comment] 2022-04-04 18:25
> Hello again! I have just performed several tests on our side to check where the problem could be and, apparently, it is a bug related to saving entities that are in unloaded chunks.
> 
> Currently, in our plugin, worlds can be saved and unloaded in two different ways:
> 
> * Using the /stop command in which worlds are saved instantly.
> * When a player disconnects and the world becomes inactive for at least 2 minutes.
> 
> In the first case and after unloading the world, restarting the server and reloading the world again there is no problem. The entities are saved and loaded correctly and without losses since the test chunk where the entities are located is occupied and loaded by the player.
> 
> The problem arises in this second case. When the player is disconnected the chunk is unloaded and, when saving, no entity appears as I have been able to verify in some debugs that I have added.
> 
> I could only check the first case by adding a tile entity in a distant chunk and disconnecting far away from it to see if it is still removed.

Could you provide some insight into what versions you're running both server side, java wise & ASWM wise (specific commit)

**Comment by samfces** [comment] 2022-04-04 18:39
> Hello again! I have just performed several tests on our side to check where the problem could be and, apparently, it is a bug related to saving entities that are in unloaded chunks.
> 
> Currently, in our plugin, worlds can be saved and unloaded in two different ways:
> 
> * Using the /stop command in which worlds are saved instantly.
> * When a player disconnects and the world becomes inactive for at least 2 minutes.
> 
> In the first case and after unloading the world, restarting the server and reloading the world again there is no problem. The entities are saved and loaded correctly and without losses since the test chunk where the entities are located is occupied and loaded by the player.
> 
> The problem arises in this second case. When the player is disconnected the chunk is unloaded and, when saving, no entity appears as I have been able to verify in some debugs that I have added.
> 
> I could only check the first case by adding a tile entity in a distant chunk and disconnecting far away from it to see if it is still removed.

**I confirm that the case I still had to check replicates the failure so I can confirm almost 99% that the problem is related to unloaded chunks.**

> Could you provide some insight into what versions you're running both server side, java wise & ASWM wise (specific commit)

**Server version:**
- Paper git-Paper-409 (MC: 1.17.1)

**Java versions on which the tests were performed:**
- Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)
- OpenJDK Runtime Environment (build 11.0.14.1+1-Ubuntu-0ubuntu1.18.04)

**ASWM version and build:**
- The /swm version command does not show the version correctly but the build used is the last one that appears in the #new-builds channel on your Discord server. (pull/97 Build ID 709)
![image](https://user-images.githubusercontent.com/26687602/161609934-c9109158-4df4-46b7-b379-6f4eada1ffbd.png)

**Comment by Paul19988** [comment] 2022-04-04 19:09
Okay so from what I can gather because of the version of paper you're running there's a bug where it will not save automatically on unload so you'll need to do this part manually just after unloading (if using the api)

**Comment by samfces** [comment] 2022-04-04 19:18
> Okay so from what I can gather because of the version of paper you're running there's a bug where it will not save automatically on unload so you'll need to do this part manually just after unloading (if using the api)

The world is already being saved **before** unloading the world. I think it cannot be saved after unloading it.

![image](https://user-images.githubusercontent.com/26687602/161615850-f22a27fa-24e5-4e97-b491-b46d5375bb7e.png)

**Comment by ComputerNerd100** [comment] 2022-04-04 19:19
> > Okay so from what I can gather because of the version of paper you're running there's a bug where it will not save automatically on unload so you'll need to do this part manually just after unloading (if using the api)
> 
> What do you mean? If we put it in a new version (1.18x paper) it should work bi

Yeah this is patched in paper 1.18, build 259 or newer should work

**Comment by ComputerNerd100** [comment] 2022-04-04 19:20
> > Okay so from what I can gather because of the version of paper you're running there's a bug where it will not save automatically on unload so you'll need to do this part manually just after unloading (if using the api)
> 
> The world is already being saved **before** unloading the world. I think it cannot be saved after unloading it.
> 
> ![image](https://user-images.githubusercontent.com/26687602/161615850-f22a27fa-24e5-4e97-b491-b46d5375bb7e.png)

The problem is that unloadWorld method from Bukkit is actually broken, And it has been since 1.14
I submitted a patch to paper, which is present in build #259 of 1.18, which fixes the bug, however it isn't backported

**Comment by aleexgheorghe** [comment] 2022-04-04 21:16
We understand, possibly what we will do is to update it directly to the latest version 1.18 of paper so that it stops giving this kind of problems. 

Is ASWM really stable in 1.18? Do you use it a lot? 

Thank you.

**Comment by samfces** [comment] 2022-04-05 07:57
> Yeah this is patched in paper 1.18, build 259 or newer should work

The problem persists using **Paper git-Paper-277 (MC: 1.18.2).**
As I said before, the problem is not with the world save using the Bukkit#unloadWorld method as it also appears using the World#save method. The problem is related to the previously mentioned, the tile entities found in unloaded chunks.

**Comment by Owen1212055** [comment] 2022-04-05 10:30
I suspected that this was the issue. Thanks for investigating, I am aware and will be working towards a fix.

**Comment by aleexgheorghe** [comment] 2022-04-05 10:35
Thank you very much Owen, we have reverted all the changes to 1.17.1. I will keep an eye on it.

**Comment by Owen1212055** [comment] 2022-04-07 23:15
Can reproduce the issue with entities, however, I still can't reproduce what is happening with tile entities (like chests) here.

**Comment by aleexgheorghe** [comment] 2022-04-08 10:39
Hi @Owen1212055 !

If you wish, I attach my configurations and my jar so you can see it in much more detail but it should be correct.

> This is how we use the API: https://gist.github.com/samfces/70244447419301b09f7ede483f962229
> Spigot configurations: https://gist.github.com/alexeses/21c446e6d896ffca04eec4b60d8a57c0
> My server version
`paper version
[12:36:27 INFO]: Checking version, please wait...
[12:36:27 INFO]: This server is running Paper version git-Paper-409 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: c53577e on ver/1.17.1)
You are running the latest version`

The problem of the chests happens from time to time, I don't know if this is the case, but possibly one problem is linked to the other.

**Comment by aleexgheorghe** [comment] 2022-04-12 09:22
Any news about the problem? There really isn't a day that goes by that an average of ten people report to me what happened. I would be willing to attach whatever is needed to try to come up with a solution. 

The error keeps happening anyway. My community is quite concerned as it has been happening a lot for about three weeks now and it is too annoying.

Thank you very much.

**Comment by Paul19988** [comment] 2022-04-12 09:48
> 

We're unable to reproduce the issue you're having, would it be possible for you to zip up to your server and send us over a copy to review and test with?

(This can be done in DM's on Discord if you wish for it to be private) (Send it to ComputerNerd100 as I'll be away from tomorrow)

**Comment by Owen1212055** [comment] 2022-04-12 10:34
> Any news about the problem? There really isn't a day that goes by that an average of ten people report to me what happened. I would be willing to attach whatever is needed to try to come up with a solution.
> 
> The error keeps happening anyway. My community is quite concerned as it has been happening a lot for about three weeks now and it is too annoying.
> 
> Thank you very much.

I’m working on a fix on and off, it should be ready soon. I’ll dedicate more time today.

**Comment by aleexgheorghe** [comment] 2022-04-12 16:35
Hi @Paul19988 and @Owen1212055 !

Thank you very much for replying me, the bug really is very simple to replicate using the same ASWM API (when downloading the world using the API or uploading it), you will see in the last posts that I have bothered to make even video of the problem, attaching all kind of logs, configurations and so on.

Unfortunately I can't attach my compressed server, it's a very valuable private project for us. I've even passed you bits of code of how I use the ASWM API, server version and everything needed. In this case @Owen1212055 was able to replicate the bug.

I am very excited to be able to test the latest version with the patch done.

Thank you very much. I hope I could have helped to get the add-on working as it should.

**Comment by Owen1212055** [comment] 2022-04-16 02:38
I have resolved the underlying issue of entities randomly disappearing, and have redone the saving process in order to prevent accessing certain things async.

I am not sure what causes tile entities to become invisible, however, I am hoping that these changes fix this issue. If this is still an issue, please comment on this issue and it will be reopened.

**Closed as completed by Owen1212055** 2022-04-16 02:38 UTC
Labels: BUG, IN PROGRESS
